# Generated by Django 4.1.7 on 2023-03-20 11:05

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0002_remove_customer_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region="UA", unique=True
            ),
        ),
    ]
