# Generated by Django 4.1.7 on 2023-03-23 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_product_digital_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="address",
            new_name="city",
        ),
    ]
