# Generated by Django 4.1.7 on 2023-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_rename_address_customer_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="np_office",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
