# Generated by Django 4.1.7 on 2023-03-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_alter_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="guest_name",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
