# Generated by Django 4.1.7 on 2023-03-27 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_customer_guest_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="guest_email",
            field=models.EmailField(blank=True, max_length=128, null=True),
        ),
    ]
