version: "3.9"

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
    depends_on:
      - mongo

  django_ecom_app:
    build:
        context: .
        dockerfile: ./Dockerfile-mongo
    env_file: .env
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             echo \"from django.contrib.auth.models import User; from store.models import Customer; User.objects.create_superuser('admin', 'admin@a.aa', 'admin', first_name='Root', last_name='Broot'); Customer.objects.create(user=User.objects.get(pk=1), phone='+380631112233', city='Kherson', np_office='404')\" | python manage.py shell &&
             gunicorn ecom_website.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./ecom_website:/usr/src/app/ecom_website
      - ./store:/usr/src/app/store
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - type: bind
        source: .env
        target: /usr/src/app/.env
      - type: bind
        source: ./manage.py
        target: /usr/src/app/manage.py
      - type: bind
        source: ./requirements.txt
        target: /usr/src/app/requirements.txt

    restart: always
    depends_on:
      - mongo

  nginx:
    image: nginx:1.23.4-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    depends_on:
      - django_ecom_app


volumes:
  mongo_data:
  static_volume:
  media_volume:
