import json
import psycopg2
import random
import asyncio
import aiohttp


async def upload_image(image_url):
    path = f"/usr/src/app/media/uploads/products/{image_url.split('/')[-1]}"
    async with aiohttp.ClientSession() as session:
        async with session.get(image_url) as response:
            if response.status == 200:
                with open(path, 'wb') as f:
                    while True:
                        chunk = await response.content.read(1024)
                        if not chunk:
                            break
                        f.write(chunk)
                        print(f"Downloaded {image_url}")
            else:
                print(f"Failed to download {image_url}")
    return None


# connect to the database
connection = psycopg2.connect(
    host="db",
    database="postgres",
    user="postgres",
    password="password",
    port=5432,
)

# # create a cursor object
cursor = connection.cursor()

# Table properties:
# Column	Type	Comment
# id	bigint Auto Increment [GENERATED BY DEFAULT AS IDENTITY]
# name	character varying(128)
# description	text
# digital	boolean NULL
# price	numeric(9,2)
# stock	integer
# image	character varying(100) NULL
# category_id	bigint

db_categories = {
    'Смартфони і мобільні телефони': 1,
    'Телевізори': 4,
    'Ігрові консолі': 6,
    'Ноутбуки': 5,
    '📱 Планшети': 7,
    'Монітори': 8,
}

# open jsonl file
with open('allo_products.jsonl') as file:
    # read each line
    for line in file:
        # load the json object
        data = json.loads(line)
        if data['product_in_stock'] != '' or not data['product_img_url']:
            continue
        name = data['product_name']
        description = data['product_description'].replace("'", "")
        price = float(data['product_price_current_uah'])

        stock = random.randint(1, 100)
        digital = False
        image = f"uploads/products/{data['product_img_url'].split('/')[-1]}"
        if len(image) > 100:
          continue

        try:
            category_id = db_categories[data['category']]
        except KeyError:
            continue
        # print each variable to the console

        # insert the data into the table
        cursor.execute(
            f"INSERT INTO store_product (name, description, digital, price, stock, image, category_id)"
            f"VALUES ('{name}', '{description}', {digital}, {price}, {stock}, '{image}', {category_id});"
        )

        upload_image(data['product_img_url'])
        print(f'Product {name} added to the database')
# commit the changes to the database
connection.commit()

# close the cursor and connection
cursor.close()
connection.close()
